// Code generated by ent, DO NOT EDIT.

package cryptodepositaddress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldUserID, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldCurrency, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldNetwork, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldAddress, v))
}

// ProviderInstanceID applies equality check predicate on the "provider_instance_id" field. It's identical to ProviderInstanceIDEQ.
func ProviderInstanceID(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldProviderInstanceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldUserID, vs...))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContainsFold(FieldCurrency, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContainsFold(FieldNetwork, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContainsFold(FieldAddress, v))
}

// ProviderInstanceIDEQ applies the EQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDNEQ applies the NEQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDNEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDIn applies the In predicate on the "provider_instance_id" field.
func ProviderInstanceIDIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDNotIn applies the NotIn predicate on the "provider_instance_id" field.
func ProviderInstanceIDNotIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDGT applies the GT predicate on the "provider_instance_id" field.
func ProviderInstanceIDGT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDGTE applies the GTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDGTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLT applies the LT predicate on the "provider_instance_id" field.
func ProviderInstanceIDLT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLTE applies the LTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDLTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldProviderInstanceID, v))
}

// ProviderInstanceIDContains applies the Contains predicate on the "provider_instance_id" field.
func ProviderInstanceIDContains(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContains(FieldProviderInstanceID, v))
}

// ProviderInstanceIDHasPrefix applies the HasPrefix predicate on the "provider_instance_id" field.
func ProviderInstanceIDHasPrefix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasPrefix(FieldProviderInstanceID, v))
}

// ProviderInstanceIDHasSuffix applies the HasSuffix predicate on the "provider_instance_id" field.
func ProviderInstanceIDHasSuffix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasSuffix(FieldProviderInstanceID, v))
}

// ProviderInstanceIDIsNil applies the IsNil predicate on the "provider_instance_id" field.
func ProviderInstanceIDIsNil() predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIsNull(FieldProviderInstanceID))
}

// ProviderInstanceIDNotNil applies the NotNil predicate on the "provider_instance_id" field.
func ProviderInstanceIDNotNil() predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotNull(FieldProviderInstanceID))
}

// ProviderInstanceIDEqualFold applies the EqualFold predicate on the "provider_instance_id" field.
func ProviderInstanceIDEqualFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEqualFold(FieldProviderInstanceID, v))
}

// ProviderInstanceIDContainsFold applies the ContainsFold predicate on the "provider_instance_id" field.
func ProviderInstanceIDContainsFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContainsFold(FieldProviderInstanceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CryptoDepositAddress) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CryptoDepositAddress) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CryptoDepositAddress) predicate.CryptoDepositAddress {
	return predicate.CryptoDepositAddress(sql.NotPredicates(p))
}
