// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptodepositaddress"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CryptoDepositAddressUpdate is the builder for updating CryptoDepositAddress entities.
type CryptoDepositAddressUpdate struct {
	config
	hooks    []Hook
	mutation *CryptoDepositAddressMutation
}

// Where appends a list predicates to the CryptoDepositAddressUpdate builder.
func (_u *CryptoDepositAddressUpdate) Where(ps ...predicate.CryptoDepositAddress) *CryptoDepositAddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CryptoDepositAddressUpdate) SetUserID(v int64) *CryptoDepositAddressUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdate) SetNillableUserID(v *int64) *CryptoDepositAddressUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CryptoDepositAddressUpdate) SetCurrency(v string) *CryptoDepositAddressUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdate) SetNillableCurrency(v *string) *CryptoDepositAddressUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *CryptoDepositAddressUpdate) SetNetwork(v string) *CryptoDepositAddressUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdate) SetNillableNetwork(v *string) *CryptoDepositAddressUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *CryptoDepositAddressUpdate) SetAddress(v string) *CryptoDepositAddressUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdate) SetNillableAddress(v *string) *CryptoDepositAddressUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *CryptoDepositAddressUpdate) SetProviderInstanceID(v string) *CryptoDepositAddressUpdate {
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdate) SetNillableProviderInstanceID(v *string) *CryptoDepositAddressUpdate {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// ClearProviderInstanceID clears the value of the "provider_instance_id" field.
func (_u *CryptoDepositAddressUpdate) ClearProviderInstanceID() *CryptoDepositAddressUpdate {
	_u.mutation.ClearProviderInstanceID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CryptoDepositAddressUpdate) SetStatus(v string) *CryptoDepositAddressUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdate) SetNillableStatus(v *string) *CryptoDepositAddressUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CryptoDepositAddressUpdate) SetUpdatedAt(v time.Time) *CryptoDepositAddressUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CryptoDepositAddressUpdate) SetUser(v *User) *CryptoDepositAddressUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CryptoDepositAddressMutation object of the builder.
func (_u *CryptoDepositAddressUpdate) Mutation() *CryptoDepositAddressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CryptoDepositAddressUpdate) ClearUser() *CryptoDepositAddressUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CryptoDepositAddressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CryptoDepositAddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CryptoDepositAddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CryptoDepositAddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CryptoDepositAddressUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cryptodepositaddress.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CryptoDepositAddressUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := cryptodepositaddress.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := cryptodepositaddress.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := cryptodepositaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderInstanceID(); ok {
		if err := cryptodepositaddress.ProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := cryptodepositaddress.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CryptoDepositAddress.user"`)
	}
	return nil
}

func (_u *CryptoDepositAddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cryptodepositaddress.Table, cryptodepositaddress.Columns, sqlgraph.NewFieldSpec(cryptodepositaddress.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(cryptodepositaddress.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(cryptodepositaddress.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(cryptodepositaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(cryptodepositaddress.FieldProviderInstanceID, field.TypeString, value)
	}
	if _u.mutation.ProviderInstanceIDCleared() {
		_spec.ClearField(cryptodepositaddress.FieldProviderInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cryptodepositaddress.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptodepositaddress.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cryptodepositaddress.UserTable,
			Columns: []string{cryptodepositaddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cryptodepositaddress.UserTable,
			Columns: []string{cryptodepositaddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cryptodepositaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CryptoDepositAddressUpdateOne is the builder for updating a single CryptoDepositAddress entity.
type CryptoDepositAddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CryptoDepositAddressMutation
}

// SetUserID sets the "user_id" field.
func (_u *CryptoDepositAddressUpdateOne) SetUserID(v int64) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdateOne) SetNillableUserID(v *int64) *CryptoDepositAddressUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CryptoDepositAddressUpdateOne) SetCurrency(v string) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdateOne) SetNillableCurrency(v *string) *CryptoDepositAddressUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *CryptoDepositAddressUpdateOne) SetNetwork(v string) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdateOne) SetNillableNetwork(v *string) *CryptoDepositAddressUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *CryptoDepositAddressUpdateOne) SetAddress(v string) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdateOne) SetNillableAddress(v *string) *CryptoDepositAddressUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *CryptoDepositAddressUpdateOne) SetProviderInstanceID(v string) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdateOne) SetNillableProviderInstanceID(v *string) *CryptoDepositAddressUpdateOne {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// ClearProviderInstanceID clears the value of the "provider_instance_id" field.
func (_u *CryptoDepositAddressUpdateOne) ClearProviderInstanceID() *CryptoDepositAddressUpdateOne {
	_u.mutation.ClearProviderInstanceID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CryptoDepositAddressUpdateOne) SetStatus(v string) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CryptoDepositAddressUpdateOne) SetNillableStatus(v *string) *CryptoDepositAddressUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CryptoDepositAddressUpdateOne) SetUpdatedAt(v time.Time) *CryptoDepositAddressUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CryptoDepositAddressUpdateOne) SetUser(v *User) *CryptoDepositAddressUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CryptoDepositAddressMutation object of the builder.
func (_u *CryptoDepositAddressUpdateOne) Mutation() *CryptoDepositAddressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CryptoDepositAddressUpdateOne) ClearUser() *CryptoDepositAddressUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CryptoDepositAddressUpdate builder.
func (_u *CryptoDepositAddressUpdateOne) Where(ps ...predicate.CryptoDepositAddress) *CryptoDepositAddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CryptoDepositAddressUpdateOne) Select(field string, fields ...string) *CryptoDepositAddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CryptoDepositAddress entity.
func (_u *CryptoDepositAddressUpdateOne) Save(ctx context.Context) (*CryptoDepositAddress, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CryptoDepositAddressUpdateOne) SaveX(ctx context.Context) *CryptoDepositAddress {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CryptoDepositAddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CryptoDepositAddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CryptoDepositAddressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cryptodepositaddress.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CryptoDepositAddressUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := cryptodepositaddress.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := cryptodepositaddress.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := cryptodepositaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderInstanceID(); ok {
		if err := cryptodepositaddress.ProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := cryptodepositaddress.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CryptoDepositAddress.user"`)
	}
	return nil
}

func (_u *CryptoDepositAddressUpdateOne) sqlSave(ctx context.Context) (_node *CryptoDepositAddress, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cryptodepositaddress.Table, cryptodepositaddress.Columns, sqlgraph.NewFieldSpec(cryptodepositaddress.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CryptoDepositAddress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cryptodepositaddress.FieldID)
		for _, f := range fields {
			if !cryptodepositaddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cryptodepositaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(cryptodepositaddress.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(cryptodepositaddress.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(cryptodepositaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(cryptodepositaddress.FieldProviderInstanceID, field.TypeString, value)
	}
	if _u.mutation.ProviderInstanceIDCleared() {
		_spec.ClearField(cryptodepositaddress.FieldProviderInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cryptodepositaddress.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptodepositaddress.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cryptodepositaddress.UserTable,
			Columns: []string{cryptodepositaddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cryptodepositaddress.UserTable,
			Columns: []string{cryptodepositaddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CryptoDepositAddress{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cryptodepositaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
