// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptodepositaddress"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CryptoDepositAddressCreate is the builder for creating a CryptoDepositAddress entity.
type CryptoDepositAddressCreate struct {
	config
	mutation *CryptoDepositAddressMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CryptoDepositAddressCreate) SetUserID(v int64) *CryptoDepositAddressCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CryptoDepositAddressCreate) SetCurrency(v string) *CryptoDepositAddressCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *CryptoDepositAddressCreate) SetNetwork(v string) *CryptoDepositAddressCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *CryptoDepositAddressCreate) SetAddress(v string) *CryptoDepositAddressCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_c *CryptoDepositAddressCreate) SetProviderInstanceID(v string) *CryptoDepositAddressCreate {
	_c.mutation.SetProviderInstanceID(v)
	return _c
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_c *CryptoDepositAddressCreate) SetNillableProviderInstanceID(v *string) *CryptoDepositAddressCreate {
	if v != nil {
		_c.SetProviderInstanceID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CryptoDepositAddressCreate) SetStatus(v string) *CryptoDepositAddressCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CryptoDepositAddressCreate) SetNillableStatus(v *string) *CryptoDepositAddressCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CryptoDepositAddressCreate) SetCreatedAt(v time.Time) *CryptoDepositAddressCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CryptoDepositAddressCreate) SetNillableCreatedAt(v *time.Time) *CryptoDepositAddressCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CryptoDepositAddressCreate) SetUpdatedAt(v time.Time) *CryptoDepositAddressCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CryptoDepositAddressCreate) SetNillableUpdatedAt(v *time.Time) *CryptoDepositAddressCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CryptoDepositAddressCreate) SetUser(v *User) *CryptoDepositAddressCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CryptoDepositAddressMutation object of the builder.
func (_c *CryptoDepositAddressCreate) Mutation() *CryptoDepositAddressMutation {
	return _c.mutation
}

// Save creates the CryptoDepositAddress in the database.
func (_c *CryptoDepositAddressCreate) Save(ctx context.Context) (*CryptoDepositAddress, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CryptoDepositAddressCreate) SaveX(ctx context.Context) *CryptoDepositAddress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoDepositAddressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoDepositAddressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CryptoDepositAddressCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := cryptodepositaddress.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cryptodepositaddress.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cryptodepositaddress.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CryptoDepositAddressCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CryptoDepositAddress.user_id"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CryptoDepositAddress.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := cryptodepositaddress.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "CryptoDepositAddress.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := cryptodepositaddress.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "CryptoDepositAddress.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := cryptodepositaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderInstanceID(); ok {
		if err := cryptodepositaddress.ProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.provider_instance_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CryptoDepositAddress.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := cryptodepositaddress.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoDepositAddress.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CryptoDepositAddress.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CryptoDepositAddress.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CryptoDepositAddress.user"`)}
	}
	return nil
}

func (_c *CryptoDepositAddressCreate) sqlSave(ctx context.Context) (*CryptoDepositAddress, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CryptoDepositAddressCreate) createSpec() (*CryptoDepositAddress, *sqlgraph.CreateSpec) {
	var (
		_node = &CryptoDepositAddress{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cryptodepositaddress.Table, sqlgraph.NewFieldSpec(cryptodepositaddress.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(cryptodepositaddress.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(cryptodepositaddress.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(cryptodepositaddress.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.ProviderInstanceID(); ok {
		_spec.SetField(cryptodepositaddress.FieldProviderInstanceID, field.TypeString, value)
		_node.ProviderInstanceID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cryptodepositaddress.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cryptodepositaddress.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptodepositaddress.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cryptodepositaddress.UserTable,
			Columns: []string{cryptodepositaddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoDepositAddress.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoDepositAddressUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoDepositAddressCreate) OnConflict(opts ...sql.ConflictOption) *CryptoDepositAddressUpsertOne {
	_c.conflict = opts
	return &CryptoDepositAddressUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoDepositAddress.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoDepositAddressCreate) OnConflictColumns(columns ...string) *CryptoDepositAddressUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoDepositAddressUpsertOne{
		create: _c,
	}
}

type (
	// CryptoDepositAddressUpsertOne is the builder for "upsert"-ing
	//  one CryptoDepositAddress node.
	CryptoDepositAddressUpsertOne struct {
		create *CryptoDepositAddressCreate
	}

	// CryptoDepositAddressUpsert is the "OnConflict" setter.
	CryptoDepositAddressUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CryptoDepositAddressUpsert) SetUserID(v int64) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateUserID() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldUserID)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CryptoDepositAddressUpsert) SetCurrency(v string) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateCurrency() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldCurrency)
	return u
}

// SetNetwork sets the "network" field.
func (u *CryptoDepositAddressUpsert) SetNetwork(v string) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateNetwork() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldNetwork)
	return u
}

// SetAddress sets the "address" field.
func (u *CryptoDepositAddressUpsert) SetAddress(v string) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateAddress() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldAddress)
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CryptoDepositAddressUpsert) SetProviderInstanceID(v string) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldProviderInstanceID, v)
	return u
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateProviderInstanceID() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldProviderInstanceID)
	return u
}

// ClearProviderInstanceID clears the value of the "provider_instance_id" field.
func (u *CryptoDepositAddressUpsert) ClearProviderInstanceID() *CryptoDepositAddressUpsert {
	u.SetNull(cryptodepositaddress.FieldProviderInstanceID)
	return u
}

// SetStatus sets the "status" field.
func (u *CryptoDepositAddressUpsert) SetStatus(v string) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateStatus() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoDepositAddressUpsert) SetUpdatedAt(v time.Time) *CryptoDepositAddressUpsert {
	u.Set(cryptodepositaddress.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsert) UpdateUpdatedAt() *CryptoDepositAddressUpsert {
	u.SetExcluded(cryptodepositaddress.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CryptoDepositAddress.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoDepositAddressUpsertOne) UpdateNewValues() *CryptoDepositAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cryptodepositaddress.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoDepositAddress.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CryptoDepositAddressUpsertOne) Ignore() *CryptoDepositAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoDepositAddressUpsertOne) DoNothing() *CryptoDepositAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoDepositAddressCreate.OnConflict
// documentation for more info.
func (u *CryptoDepositAddressUpsertOne) Update(set func(*CryptoDepositAddressUpsert)) *CryptoDepositAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoDepositAddressUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CryptoDepositAddressUpsertOne) SetUserID(v int64) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateUserID() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateUserID()
	})
}

// SetCurrency sets the "currency" field.
func (u *CryptoDepositAddressUpsertOne) SetCurrency(v string) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateCurrency() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateCurrency()
	})
}

// SetNetwork sets the "network" field.
func (u *CryptoDepositAddressUpsertOne) SetNetwork(v string) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateNetwork() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateNetwork()
	})
}

// SetAddress sets the "address" field.
func (u *CryptoDepositAddressUpsertOne) SetAddress(v string) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateAddress() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateAddress()
	})
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CryptoDepositAddressUpsertOne) SetProviderInstanceID(v string) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateProviderInstanceID() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// ClearProviderInstanceID clears the value of the "provider_instance_id" field.
func (u *CryptoDepositAddressUpsertOne) ClearProviderInstanceID() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.ClearProviderInstanceID()
	})
}

// SetStatus sets the "status" field.
func (u *CryptoDepositAddressUpsertOne) SetStatus(v string) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateStatus() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoDepositAddressUpsertOne) SetUpdatedAt(v time.Time) *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertOne) UpdateUpdatedAt() *CryptoDepositAddressUpsertOne {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CryptoDepositAddressUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoDepositAddressCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoDepositAddressUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CryptoDepositAddressUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CryptoDepositAddressUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CryptoDepositAddressCreateBulk is the builder for creating many CryptoDepositAddress entities in bulk.
type CryptoDepositAddressCreateBulk struct {
	config
	err      error
	builders []*CryptoDepositAddressCreate
	conflict []sql.ConflictOption
}

// Save creates the CryptoDepositAddress entities in the database.
func (_c *CryptoDepositAddressCreateBulk) Save(ctx context.Context) ([]*CryptoDepositAddress, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CryptoDepositAddress, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CryptoDepositAddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CryptoDepositAddressCreateBulk) SaveX(ctx context.Context) []*CryptoDepositAddress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoDepositAddressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoDepositAddressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoDepositAddress.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoDepositAddressUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoDepositAddressCreateBulk) OnConflict(opts ...sql.ConflictOption) *CryptoDepositAddressUpsertBulk {
	_c.conflict = opts
	return &CryptoDepositAddressUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoDepositAddress.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoDepositAddressCreateBulk) OnConflictColumns(columns ...string) *CryptoDepositAddressUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoDepositAddressUpsertBulk{
		create: _c,
	}
}

// CryptoDepositAddressUpsertBulk is the builder for "upsert"-ing
// a bulk of CryptoDepositAddress nodes.
type CryptoDepositAddressUpsertBulk struct {
	create *CryptoDepositAddressCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CryptoDepositAddress.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoDepositAddressUpsertBulk) UpdateNewValues() *CryptoDepositAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cryptodepositaddress.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoDepositAddress.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CryptoDepositAddressUpsertBulk) Ignore() *CryptoDepositAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoDepositAddressUpsertBulk) DoNothing() *CryptoDepositAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoDepositAddressCreateBulk.OnConflict
// documentation for more info.
func (u *CryptoDepositAddressUpsertBulk) Update(set func(*CryptoDepositAddressUpsert)) *CryptoDepositAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoDepositAddressUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CryptoDepositAddressUpsertBulk) SetUserID(v int64) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateUserID() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateUserID()
	})
}

// SetCurrency sets the "currency" field.
func (u *CryptoDepositAddressUpsertBulk) SetCurrency(v string) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateCurrency() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateCurrency()
	})
}

// SetNetwork sets the "network" field.
func (u *CryptoDepositAddressUpsertBulk) SetNetwork(v string) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateNetwork() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateNetwork()
	})
}

// SetAddress sets the "address" field.
func (u *CryptoDepositAddressUpsertBulk) SetAddress(v string) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateAddress() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateAddress()
	})
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *CryptoDepositAddressUpsertBulk) SetProviderInstanceID(v string) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateProviderInstanceID() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// ClearProviderInstanceID clears the value of the "provider_instance_id" field.
func (u *CryptoDepositAddressUpsertBulk) ClearProviderInstanceID() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.ClearProviderInstanceID()
	})
}

// SetStatus sets the "status" field.
func (u *CryptoDepositAddressUpsertBulk) SetStatus(v string) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateStatus() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoDepositAddressUpsertBulk) SetUpdatedAt(v time.Time) *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoDepositAddressUpsertBulk) UpdateUpdatedAt() *CryptoDepositAddressUpsertBulk {
	return u.Update(func(s *CryptoDepositAddressUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CryptoDepositAddressUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CryptoDepositAddressCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoDepositAddressCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoDepositAddressUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
