// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/cryptodepositaddress"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CryptoDepositAddress is the model entity for the CryptoDepositAddress schema.
type CryptoDepositAddress struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// 币种，如 'USDT', 'BTC', 'ETH'
	Currency string `json:"currency,omitempty"`
	// 区块链网络，如 'TRC20', 'ERC20', 'BEP20'
	Network string `json:"network,omitempty"`
	// 充值地址
	Address string `json:"address,omitempty"`
	// 支付服务商实例 ID
	ProviderInstanceID *string `json:"provider_instance_id,omitempty"`
	// 地址状态：active（活跃）、inactive（停用）、expired（过期）
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CryptoDepositAddressQuery when eager-loading is set.
	Edges        CryptoDepositAddressEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CryptoDepositAddressEdges holds the relations/edges for other nodes in the graph.
type CryptoDepositAddressEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CryptoDepositAddressEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CryptoDepositAddress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cryptodepositaddress.FieldID, cryptodepositaddress.FieldUserID:
			values[i] = new(sql.NullInt64)
		case cryptodepositaddress.FieldCurrency, cryptodepositaddress.FieldNetwork, cryptodepositaddress.FieldAddress, cryptodepositaddress.FieldProviderInstanceID, cryptodepositaddress.FieldStatus:
			values[i] = new(sql.NullString)
		case cryptodepositaddress.FieldCreatedAt, cryptodepositaddress.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CryptoDepositAddress fields.
func (_m *CryptoDepositAddress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cryptodepositaddress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cryptodepositaddress.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case cryptodepositaddress.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case cryptodepositaddress.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case cryptodepositaddress.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case cryptodepositaddress.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = new(string)
				*_m.ProviderInstanceID = value.String
			}
		case cryptodepositaddress.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case cryptodepositaddress.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cryptodepositaddress.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CryptoDepositAddress.
// This includes values selected through modifiers, order, etc.
func (_m *CryptoDepositAddress) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CryptoDepositAddress entity.
func (_m *CryptoDepositAddress) QueryUser() *UserQuery {
	return NewCryptoDepositAddressClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CryptoDepositAddress.
// Note that you need to call CryptoDepositAddress.Unwrap() before calling this method if this CryptoDepositAddress
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CryptoDepositAddress) Update() *CryptoDepositAddressUpdateOne {
	return NewCryptoDepositAddressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CryptoDepositAddress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CryptoDepositAddress) Unwrap() *CryptoDepositAddress {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CryptoDepositAddress is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CryptoDepositAddress) String() string {
	var builder strings.Builder
	builder.WriteString("CryptoDepositAddress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	if v := _m.ProviderInstanceID; v != nil {
		builder.WriteString("provider_instance_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CryptoDepositAddresses is a parsable slice of CryptoDepositAddress.
type CryptoDepositAddresses []*CryptoDepositAddress
